/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "can.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x585_mag_output(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* x: start-bit 0, length 16, endianess intel, scaling 0.000174533, offset -3.49066 */
	x = ((uint16_t)(o->can_0x585_mag_output.x)) & 0xffff;
	i |= x;
	/* y: start-bit 24, length 16, endianess intel, scaling 0.000174533, offset -3.49066 */
	x = ((uint16_t)(o->can_0x585_mag_output.y)) & 0xffff;
	x <<= 24; 
	i |= x;
	/* z: start-bit 48, length 16, endianess intel, scaling 0.000174533, offset -3.49066 */
	x = ((uint16_t)(o->can_0x585_mag_output.z)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x585_mag_output_tx = 1;
	return 8;
}

static int unpack_can_0x585_mag_output(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* x: start-bit 0, length 16, endianess intel, scaling 0.000174533, offset -3.49066 */
	x = i & 0xffff;
	o->can_0x585_mag_output.x = x;
	/* y: start-bit 24, length 16, endianess intel, scaling 0.000174533, offset -3.49066 */
	x = (i >> 24) & 0xffff;
	o->can_0x585_mag_output.y = x;
	/* z: start-bit 48, length 16, endianess intel, scaling 0.000174533, offset -3.49066 */
	x = (i >> 48) & 0xffff;
	o->can_0x585_mag_output.z = x;
	o->can_0x585_mag_output_rx = 1;
	o->can_0x585_mag_output_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x585_x(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x585_mag_output.x);
	rval *= 0.000174533;
	rval += -3.49066;
	*out = rval;
	return 0;
}

int encode_can_0x585_x(can_obj_can_h_t *o, double in) {
	assert(o);
	in += 3.49066;
	in *= 5729.58;
	o->can_0x585_mag_output.x = in;
	return 0;
}

int decode_can_0x585_y(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x585_mag_output.y);
	rval *= 0.000174533;
	rval += -3.49066;
	*out = rval;
	return 0;
}

int encode_can_0x585_y(can_obj_can_h_t *o, double in) {
	assert(o);
	in += 3.49066;
	in *= 5729.58;
	o->can_0x585_mag_output.y = in;
	return 0;
}

int decode_can_0x585_z(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x585_mag_output.z);
	rval *= 0.000174533;
	rval += -3.49066;
	*out = rval;
	return 0;
}

int encode_can_0x585_z(can_obj_can_h_t *o, double in) {
	assert(o);
	in += 3.49066;
	in *= 5729.58;
	o->can_0x585_mag_output.z = in;
	return 0;
}

int print_can_0x585_mag_output(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "x = (wire: %.0f)\n", (double)(o->can_0x585_mag_output.x)));
	r = print_helper(r, fprintf(output, "y = (wire: %.0f)\n", (double)(o->can_0x585_mag_output.y)));
	r = print_helper(r, fprintf(output, "z = (wire: %.0f)\n", (double)(o->can_0x585_mag_output.z)));
	return r;
}

static int pack_can_0xa05_motor_state(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* engine_speed: start-bit 24, length 16, endianess intel, scaling 0.25, offset 0 */
	x = ((uint16_t)(o->can_0xa05_motor_state.engine_speed)) & 0xffff;
	x <<= 24; 
	i |= x;
	/* motor_index: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0xa05_motor_state.motor_index)) & 0xff;
	i |= x;
	/* valid_check: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0xa05_motor_state.valid_check)) & 0xff;
	x <<= 8; 
	i |= x;
	/* motor_status: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0xa05_motor_state.motor_status)) & 0xff;
	x <<= 16; 
	i |= x;
	/* motor_torque: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0xa05_motor_state.motor_torque)) & 0xff;
	x <<= 40; 
	i |= x;
	/* motor_throttle: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0xa05_motor_state.motor_throttle)) & 0xff;
	x <<= 48; 
	i |= x;
	/* motor_gear: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0xa05_motor_state.motor_gear)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0xa05_motor_state_tx = 1;
	return 8;
}

static int unpack_can_0xa05_motor_state(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* engine_speed: start-bit 24, length 16, endianess intel, scaling 0.25, offset 0 */
	x = (i >> 24) & 0xffff;
	o->can_0xa05_motor_state.engine_speed = x;
	/* motor_index: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0xa05_motor_state.motor_index = x;
	/* valid_check: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0xa05_motor_state.valid_check = x;
	/* motor_status: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0xa05_motor_state.motor_status = x;
	/* motor_torque: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0xa05_motor_state.motor_torque = x;
	/* motor_throttle: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0xa05_motor_state.motor_throttle = x;
	/* motor_gear: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0xa05_motor_state.motor_gear = x;
	o->can_0xa05_motor_state_rx = 1;
	o->can_0xa05_motor_state_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0xa05_engine_speed(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0xa05_motor_state.engine_speed);
	rval *= 0.25;
	*out = rval;
	return 0;
}

int encode_can_0xa05_engine_speed(can_obj_can_h_t *o, double in) {
	assert(o);
	in *= 4;
	o->can_0xa05_motor_state.engine_speed = in;
	return 0;
}

int decode_can_0xa05_motor_index(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0xa05_motor_state.motor_index);
	*out = rval;
	return 0;
}

int encode_can_0xa05_motor_index(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0xa05_motor_state.motor_index = in;
	return 0;
}

int decode_can_0xa05_valid_check(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0xa05_motor_state.valid_check);
	*out = rval;
	return 0;
}

int encode_can_0xa05_valid_check(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0xa05_motor_state.valid_check = in;
	return 0;
}

int decode_can_0xa05_motor_status(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0xa05_motor_state.motor_status);
	*out = rval;
	return 0;
}

int encode_can_0xa05_motor_status(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0xa05_motor_state.motor_status = in;
	return 0;
}

int decode_can_0xa05_motor_torque(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0xa05_motor_state.motor_torque);
	*out = rval;
	return 0;
}

int encode_can_0xa05_motor_torque(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0xa05_motor_state.motor_torque = in;
	return 0;
}

int decode_can_0xa05_motor_throttle(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0xa05_motor_state.motor_throttle);
	*out = rval;
	return 0;
}

int encode_can_0xa05_motor_throttle(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0xa05_motor_state.motor_throttle = in;
	return 0;
}

int decode_can_0xa05_motor_gear(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0xa05_motor_state.motor_gear);
	*out = rval;
	return 0;
}

int encode_can_0xa05_motor_gear(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0xa05_motor_state.motor_gear = in;
	return 0;
}

int print_can_0xa05_motor_state(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "engine_speed = (wire: %.0f)\n", (double)(o->can_0xa05_motor_state.engine_speed)));
	r = print_helper(r, fprintf(output, "motor_index = (wire: %.0f)\n", (double)(o->can_0xa05_motor_state.motor_index)));
	r = print_helper(r, fprintf(output, "valid_check = (wire: %.0f)\n", (double)(o->can_0xa05_motor_state.valid_check)));
	r = print_helper(r, fprintf(output, "motor_status = (wire: %.0f)\n", (double)(o->can_0xa05_motor_state.motor_status)));
	r = print_helper(r, fprintf(output, "motor_torque = (wire: %.0f)\n", (double)(o->can_0xa05_motor_state.motor_torque)));
	r = print_helper(r, fprintf(output, "motor_throttle = (wire: %.0f)\n", (double)(o->can_0xa05_motor_state.motor_throttle)));
	r = print_helper(r, fprintf(output, "motor_gear = (wire: %.0f)\n", (double)(o->can_0xa05_motor_state.motor_gear)));
	return r;
}

static int pack_can_0x18904001_batt_1_overall_status(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* cumulative_voltage: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904001_batt_1_overall_status.cumulative_voltage)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* collecting_voltage: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904001_batt_1_overall_status.collecting_voltage)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* current: start-bit 39, length 16, endianess motorola, scaling 0.1, offset -3000 */
	x = ((uint16_t)(o->can_0x18904001_batt_1_overall_status.current)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* soc: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904001_batt_1_overall_status.soc)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x18904001_batt_1_overall_status_tx = 1;
	return 8;
}

static int unpack_can_0x18904001_batt_1_overall_status(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* cumulative_voltage: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x18904001_batt_1_overall_status.cumulative_voltage = x;
	/* collecting_voltage: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x18904001_batt_1_overall_status.collecting_voltage = x;
	/* current: start-bit 39, length 16, endianess motorola, scaling 0.1, offset -3000 */
	x = (m >> 16) & 0xffff;
	o->can_0x18904001_batt_1_overall_status.current = x;
	/* soc: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = m & 0xffff;
	o->can_0x18904001_batt_1_overall_status.soc = x;
	o->can_0x18904001_batt_1_overall_status_rx = 1;
	o->can_0x18904001_batt_1_overall_status_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x18904001_cumulative_voltage(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904001_batt_1_overall_status.cumulative_voltage);
	rval *= 0.1;
	if (rval <= 60) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904001_cumulative_voltage(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904001_batt_1_overall_status.cumulative_voltage = 0;
	if (in > 60)
		return -1;
	in *= 10;
	o->can_0x18904001_batt_1_overall_status.cumulative_voltage = in;
	return 0;
}

int decode_can_0x18904001_collecting_voltage(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904001_batt_1_overall_status.collecting_voltage);
	rval *= 0.1;
	if (rval <= 60) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904001_collecting_voltage(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904001_batt_1_overall_status.collecting_voltage = 0;
	if (in > 60)
		return -1;
	in *= 10;
	o->can_0x18904001_batt_1_overall_status.collecting_voltage = in;
	return 0;
}

int decode_can_0x18904001_current(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904001_batt_1_overall_status.current);
	rval *= 0.1;
	rval += -3000;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904001_current(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904001_batt_1_overall_status.current = 0;
	if (in > 60000)
		return -1;
	in += 3000;
	in *= 10;
	o->can_0x18904001_batt_1_overall_status.current = in;
	return 0;
}

int decode_can_0x18904001_soc(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904001_batt_1_overall_status.soc);
	rval *= 0.1;
	if (rval <= 1000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904001_soc(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904001_batt_1_overall_status.soc = 0;
	if (in > 1000)
		return -1;
	in *= 10;
	o->can_0x18904001_batt_1_overall_status.soc = in;
	return 0;
}

int print_can_0x18904001_batt_1_overall_status(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "cumulative_voltage = (wire: %.0f)\n", (double)(o->can_0x18904001_batt_1_overall_status.cumulative_voltage)));
	r = print_helper(r, fprintf(output, "collecting_voltage = (wire: %.0f)\n", (double)(o->can_0x18904001_batt_1_overall_status.collecting_voltage)));
	r = print_helper(r, fprintf(output, "current = (wire: %.0f)\n", (double)(o->can_0x18904001_batt_1_overall_status.current)));
	r = print_helper(r, fprintf(output, "soc = (wire: %.0f)\n", (double)(o->can_0x18904001_batt_1_overall_status.soc)));
	return r;
}

static int pack_can_0x18904002_batt_2_overall_status(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* cumulative_voltage: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904002_batt_2_overall_status.cumulative_voltage)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* collecting_voltage: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904002_batt_2_overall_status.collecting_voltage)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* current: start-bit 39, length 16, endianess motorola, scaling 0.1, offset -3000 */
	x = ((uint16_t)(o->can_0x18904002_batt_2_overall_status.current)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* soc: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904002_batt_2_overall_status.soc)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x18904002_batt_2_overall_status_tx = 1;
	return 8;
}

static int unpack_can_0x18904002_batt_2_overall_status(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* cumulative_voltage: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x18904002_batt_2_overall_status.cumulative_voltage = x;
	/* collecting_voltage: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x18904002_batt_2_overall_status.collecting_voltage = x;
	/* current: start-bit 39, length 16, endianess motorola, scaling 0.1, offset -3000 */
	x = (m >> 16) & 0xffff;
	o->can_0x18904002_batt_2_overall_status.current = x;
	/* soc: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = m & 0xffff;
	o->can_0x18904002_batt_2_overall_status.soc = x;
	o->can_0x18904002_batt_2_overall_status_rx = 1;
	o->can_0x18904002_batt_2_overall_status_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x18904002_cumulative_voltage(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904002_batt_2_overall_status.cumulative_voltage);
	rval *= 0.1;
	if (rval <= 60) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904002_cumulative_voltage(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904002_batt_2_overall_status.cumulative_voltage = 0;
	if (in > 60)
		return -1;
	in *= 10;
	o->can_0x18904002_batt_2_overall_status.cumulative_voltage = in;
	return 0;
}

int decode_can_0x18904002_collecting_voltage(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904002_batt_2_overall_status.collecting_voltage);
	rval *= 0.1;
	if (rval <= 60) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904002_collecting_voltage(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904002_batt_2_overall_status.collecting_voltage = 0;
	if (in > 60)
		return -1;
	in *= 10;
	o->can_0x18904002_batt_2_overall_status.collecting_voltage = in;
	return 0;
}

int decode_can_0x18904002_current(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904002_batt_2_overall_status.current);
	rval *= 0.1;
	rval += -3000;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904002_current(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904002_batt_2_overall_status.current = 0;
	if (in > 60000)
		return -1;
	in += 3000;
	in *= 10;
	o->can_0x18904002_batt_2_overall_status.current = in;
	return 0;
}

int decode_can_0x18904002_soc(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904002_batt_2_overall_status.soc);
	rval *= 0.1;
	if (rval <= 1000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904002_soc(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904002_batt_2_overall_status.soc = 0;
	if (in > 1000)
		return -1;
	in *= 10;
	o->can_0x18904002_batt_2_overall_status.soc = in;
	return 0;
}

int print_can_0x18904002_batt_2_overall_status(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "cumulative_voltage = (wire: %.0f)\n", (double)(o->can_0x18904002_batt_2_overall_status.cumulative_voltage)));
	r = print_helper(r, fprintf(output, "collecting_voltage = (wire: %.0f)\n", (double)(o->can_0x18904002_batt_2_overall_status.collecting_voltage)));
	r = print_helper(r, fprintf(output, "current = (wire: %.0f)\n", (double)(o->can_0x18904002_batt_2_overall_status.current)));
	r = print_helper(r, fprintf(output, "soc = (wire: %.0f)\n", (double)(o->can_0x18904002_batt_2_overall_status.soc)));
	return r;
}

static int pack_can_0x18904003_batt_3_overall_status(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* cumulative_voltage: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904003_batt_3_overall_status.cumulative_voltage)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* collecting_voltage: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904003_batt_3_overall_status.collecting_voltage)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* current: start-bit 39, length 16, endianess motorola, scaling 0.1, offset -3000 */
	x = ((uint16_t)(o->can_0x18904003_batt_3_overall_status.current)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* soc: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904003_batt_3_overall_status.soc)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x18904003_batt_3_overall_status_tx = 1;
	return 8;
}

static int unpack_can_0x18904003_batt_3_overall_status(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* cumulative_voltage: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x18904003_batt_3_overall_status.cumulative_voltage = x;
	/* collecting_voltage: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x18904003_batt_3_overall_status.collecting_voltage = x;
	/* current: start-bit 39, length 16, endianess motorola, scaling 0.1, offset -3000 */
	x = (m >> 16) & 0xffff;
	o->can_0x18904003_batt_3_overall_status.current = x;
	/* soc: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = m & 0xffff;
	o->can_0x18904003_batt_3_overall_status.soc = x;
	o->can_0x18904003_batt_3_overall_status_rx = 1;
	o->can_0x18904003_batt_3_overall_status_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x18904003_cumulative_voltage(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904003_batt_3_overall_status.cumulative_voltage);
	rval *= 0.1;
	if (rval <= 60) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904003_cumulative_voltage(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904003_batt_3_overall_status.cumulative_voltage = 0;
	if (in > 60)
		return -1;
	in *= 10;
	o->can_0x18904003_batt_3_overall_status.cumulative_voltage = in;
	return 0;
}

int decode_can_0x18904003_collecting_voltage(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904003_batt_3_overall_status.collecting_voltage);
	rval *= 0.1;
	if (rval <= 60) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904003_collecting_voltage(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904003_batt_3_overall_status.collecting_voltage = 0;
	if (in > 60)
		return -1;
	in *= 10;
	o->can_0x18904003_batt_3_overall_status.collecting_voltage = in;
	return 0;
}

int decode_can_0x18904003_current(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904003_batt_3_overall_status.current);
	rval *= 0.1;
	rval += -3000;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904003_current(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904003_batt_3_overall_status.current = 0;
	if (in > 60000)
		return -1;
	in += 3000;
	in *= 10;
	o->can_0x18904003_batt_3_overall_status.current = in;
	return 0;
}

int decode_can_0x18904003_soc(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904003_batt_3_overall_status.soc);
	rval *= 0.1;
	if (rval <= 1000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904003_soc(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904003_batt_3_overall_status.soc = 0;
	if (in > 1000)
		return -1;
	in *= 10;
	o->can_0x18904003_batt_3_overall_status.soc = in;
	return 0;
}

int print_can_0x18904003_batt_3_overall_status(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "cumulative_voltage = (wire: %.0f)\n", (double)(o->can_0x18904003_batt_3_overall_status.cumulative_voltage)));
	r = print_helper(r, fprintf(output, "collecting_voltage = (wire: %.0f)\n", (double)(o->can_0x18904003_batt_3_overall_status.collecting_voltage)));
	r = print_helper(r, fprintf(output, "current = (wire: %.0f)\n", (double)(o->can_0x18904003_batt_3_overall_status.current)));
	r = print_helper(r, fprintf(output, "soc = (wire: %.0f)\n", (double)(o->can_0x18904003_batt_3_overall_status.soc)));
	return r;
}

static int pack_can_0x18904004_batt_4_overall_status(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* cumulative_voltage: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904004_batt_4_overall_status.cumulative_voltage)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* collecting_voltage: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904004_batt_4_overall_status.collecting_voltage)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* current: start-bit 39, length 16, endianess motorola, scaling 0.1, offset -3000 */
	x = ((uint16_t)(o->can_0x18904004_batt_4_overall_status.current)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* soc: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x18904004_batt_4_overall_status.soc)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x18904004_batt_4_overall_status_tx = 1;
	return 8;
}

static int unpack_can_0x18904004_batt_4_overall_status(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* cumulative_voltage: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x18904004_batt_4_overall_status.cumulative_voltage = x;
	/* collecting_voltage: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x18904004_batt_4_overall_status.collecting_voltage = x;
	/* current: start-bit 39, length 16, endianess motorola, scaling 0.1, offset -3000 */
	x = (m >> 16) & 0xffff;
	o->can_0x18904004_batt_4_overall_status.current = x;
	/* soc: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = m & 0xffff;
	o->can_0x18904004_batt_4_overall_status.soc = x;
	o->can_0x18904004_batt_4_overall_status_rx = 1;
	o->can_0x18904004_batt_4_overall_status_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x18904004_cumulative_voltage(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904004_batt_4_overall_status.cumulative_voltage);
	rval *= 0.1;
	if (rval <= 60) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904004_cumulative_voltage(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904004_batt_4_overall_status.cumulative_voltage = 0;
	if (in > 60)
		return -1;
	in *= 10;
	o->can_0x18904004_batt_4_overall_status.cumulative_voltage = in;
	return 0;
}

int decode_can_0x18904004_collecting_voltage(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904004_batt_4_overall_status.collecting_voltage);
	rval *= 0.1;
	if (rval <= 60) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904004_collecting_voltage(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904004_batt_4_overall_status.collecting_voltage = 0;
	if (in > 60)
		return -1;
	in *= 10;
	o->can_0x18904004_batt_4_overall_status.collecting_voltage = in;
	return 0;
}

int decode_can_0x18904004_current(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904004_batt_4_overall_status.current);
	rval *= 0.1;
	rval += -3000;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904004_current(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904004_batt_4_overall_status.current = 0;
	if (in > 60000)
		return -1;
	in += 3000;
	in *= 10;
	o->can_0x18904004_batt_4_overall_status.current = in;
	return 0;
}

int decode_can_0x18904004_soc(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18904004_batt_4_overall_status.soc);
	rval *= 0.1;
	if (rval <= 1000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18904004_soc(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18904004_batt_4_overall_status.soc = 0;
	if (in > 1000)
		return -1;
	in *= 10;
	o->can_0x18904004_batt_4_overall_status.soc = in;
	return 0;
}

int print_can_0x18904004_batt_4_overall_status(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "cumulative_voltage = (wire: %.0f)\n", (double)(o->can_0x18904004_batt_4_overall_status.cumulative_voltage)));
	r = print_helper(r, fprintf(output, "collecting_voltage = (wire: %.0f)\n", (double)(o->can_0x18904004_batt_4_overall_status.collecting_voltage)));
	r = print_helper(r, fprintf(output, "current = (wire: %.0f)\n", (double)(o->can_0x18904004_batt_4_overall_status.current)));
	r = print_helper(r, fprintf(output, "soc = (wire: %.0f)\n", (double)(o->can_0x18904004_batt_4_overall_status.soc)));
	return r;
}

static int pack_can_0x18914001_batt_1_cell_status(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* max_volt: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x18914001_batt_1_cell_status.max_volt)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* min_volt: start-bit 31, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x18914001_batt_1_cell_status.min_volt)) & 0xffff;
	x <<= 24; 
	m |= x;
	/* max_volt_id: start-bit 23, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x18914001_batt_1_cell_status.max_volt_id)) & 0xff;
	x <<= 40; 
	m |= x;
	/* min_volt_id: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x18914001_batt_1_cell_status.min_volt_id)) & 0xff;
	x <<= 16; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x18914001_batt_1_cell_status_tx = 1;
	return 8;
}

static int unpack_can_0x18914001_batt_1_cell_status(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* max_volt: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x18914001_batt_1_cell_status.max_volt = x;
	/* min_volt: start-bit 31, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 24) & 0xffff;
	o->can_0x18914001_batt_1_cell_status.min_volt = x;
	/* max_volt_id: start-bit 23, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 40) & 0xff;
	o->can_0x18914001_batt_1_cell_status.max_volt_id = x;
	/* min_volt_id: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 16) & 0xff;
	o->can_0x18914001_batt_1_cell_status.min_volt_id = x;
	o->can_0x18914001_batt_1_cell_status_rx = 1;
	o->can_0x18914001_batt_1_cell_status_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x18914001_max_volt(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18914001_batt_1_cell_status.max_volt);
	rval *= 0.001;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18914001_max_volt(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18914001_batt_1_cell_status.max_volt = 0;
	if (in > 60000)
		return -1;
	in *= 1000;
	o->can_0x18914001_batt_1_cell_status.max_volt = in;
	return 0;
}

int decode_can_0x18914001_min_volt(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18914001_batt_1_cell_status.min_volt);
	rval *= 0.001;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18914001_min_volt(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18914001_batt_1_cell_status.min_volt = 0;
	if (in > 60000)
		return -1;
	in *= 1000;
	o->can_0x18914001_batt_1_cell_status.min_volt = in;
	return 0;
}

int decode_can_0x18914001_max_volt_id(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x18914001_batt_1_cell_status.max_volt_id);
	if (rval <= 63) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x18914001_max_volt_id(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x18914001_batt_1_cell_status.max_volt_id = 0;
	if (in > 63)
		return -1;
	o->can_0x18914001_batt_1_cell_status.max_volt_id = in;
	return 0;
}

int decode_can_0x18914001_min_volt_id(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x18914001_batt_1_cell_status.min_volt_id);
	if (rval <= 63) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x18914001_min_volt_id(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x18914001_batt_1_cell_status.min_volt_id = 0;
	if (in > 63)
		return -1;
	o->can_0x18914001_batt_1_cell_status.min_volt_id = in;
	return 0;
}

int print_can_0x18914001_batt_1_cell_status(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_volt = (wire: %.0f)\n", (double)(o->can_0x18914001_batt_1_cell_status.max_volt)));
	r = print_helper(r, fprintf(output, "min_volt = (wire: %.0f)\n", (double)(o->can_0x18914001_batt_1_cell_status.min_volt)));
	r = print_helper(r, fprintf(output, "max_volt_id = (wire: %.0f)\n", (double)(o->can_0x18914001_batt_1_cell_status.max_volt_id)));
	r = print_helper(r, fprintf(output, "min_volt_id = (wire: %.0f)\n", (double)(o->can_0x18914001_batt_1_cell_status.min_volt_id)));
	return r;
}

static int pack_can_0x18914002_batt_2_cell_status(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* max_volt: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x18914002_batt_2_cell_status.max_volt)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* min_volt: start-bit 31, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x18914002_batt_2_cell_status.min_volt)) & 0xffff;
	x <<= 24; 
	m |= x;
	/* max_volt_id: start-bit 23, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x18914002_batt_2_cell_status.max_volt_id)) & 0xff;
	x <<= 40; 
	m |= x;
	/* min_volt_id: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x18914002_batt_2_cell_status.min_volt_id)) & 0xff;
	x <<= 16; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x18914002_batt_2_cell_status_tx = 1;
	return 8;
}

static int unpack_can_0x18914002_batt_2_cell_status(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* max_volt: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x18914002_batt_2_cell_status.max_volt = x;
	/* min_volt: start-bit 31, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 24) & 0xffff;
	o->can_0x18914002_batt_2_cell_status.min_volt = x;
	/* max_volt_id: start-bit 23, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 40) & 0xff;
	o->can_0x18914002_batt_2_cell_status.max_volt_id = x;
	/* min_volt_id: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 16) & 0xff;
	o->can_0x18914002_batt_2_cell_status.min_volt_id = x;
	o->can_0x18914002_batt_2_cell_status_rx = 1;
	o->can_0x18914002_batt_2_cell_status_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x18914002_max_volt(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18914002_batt_2_cell_status.max_volt);
	rval *= 0.001;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18914002_max_volt(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18914002_batt_2_cell_status.max_volt = 0;
	if (in > 60000)
		return -1;
	in *= 1000;
	o->can_0x18914002_batt_2_cell_status.max_volt = in;
	return 0;
}

int decode_can_0x18914002_min_volt(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18914002_batt_2_cell_status.min_volt);
	rval *= 0.001;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18914002_min_volt(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18914002_batt_2_cell_status.min_volt = 0;
	if (in > 60000)
		return -1;
	in *= 1000;
	o->can_0x18914002_batt_2_cell_status.min_volt = in;
	return 0;
}

int decode_can_0x18914002_max_volt_id(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x18914002_batt_2_cell_status.max_volt_id);
	if (rval <= 63) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x18914002_max_volt_id(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x18914002_batt_2_cell_status.max_volt_id = 0;
	if (in > 63)
		return -1;
	o->can_0x18914002_batt_2_cell_status.max_volt_id = in;
	return 0;
}

int decode_can_0x18914002_min_volt_id(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x18914002_batt_2_cell_status.min_volt_id);
	if (rval <= 63) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x18914002_min_volt_id(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x18914002_batt_2_cell_status.min_volt_id = 0;
	if (in > 63)
		return -1;
	o->can_0x18914002_batt_2_cell_status.min_volt_id = in;
	return 0;
}

int print_can_0x18914002_batt_2_cell_status(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_volt = (wire: %.0f)\n", (double)(o->can_0x18914002_batt_2_cell_status.max_volt)));
	r = print_helper(r, fprintf(output, "min_volt = (wire: %.0f)\n", (double)(o->can_0x18914002_batt_2_cell_status.min_volt)));
	r = print_helper(r, fprintf(output, "max_volt_id = (wire: %.0f)\n", (double)(o->can_0x18914002_batt_2_cell_status.max_volt_id)));
	r = print_helper(r, fprintf(output, "min_volt_id = (wire: %.0f)\n", (double)(o->can_0x18914002_batt_2_cell_status.min_volt_id)));
	return r;
}

static int pack_can_0x18914003_batt_3_cell_status(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* max_volt: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x18914003_batt_3_cell_status.max_volt)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* min_volt: start-bit 31, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x18914003_batt_3_cell_status.min_volt)) & 0xffff;
	x <<= 24; 
	m |= x;
	/* max_volt_id: start-bit 23, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x18914003_batt_3_cell_status.max_volt_id)) & 0xff;
	x <<= 40; 
	m |= x;
	/* min_volt_id: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x18914003_batt_3_cell_status.min_volt_id)) & 0xff;
	x <<= 16; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x18914003_batt_3_cell_status_tx = 1;
	return 8;
}

static int unpack_can_0x18914003_batt_3_cell_status(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* max_volt: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x18914003_batt_3_cell_status.max_volt = x;
	/* min_volt: start-bit 31, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 24) & 0xffff;
	o->can_0x18914003_batt_3_cell_status.min_volt = x;
	/* max_volt_id: start-bit 23, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 40) & 0xff;
	o->can_0x18914003_batt_3_cell_status.max_volt_id = x;
	/* min_volt_id: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 16) & 0xff;
	o->can_0x18914003_batt_3_cell_status.min_volt_id = x;
	o->can_0x18914003_batt_3_cell_status_rx = 1;
	o->can_0x18914003_batt_3_cell_status_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x18914003_max_volt(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18914003_batt_3_cell_status.max_volt);
	rval *= 0.001;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18914003_max_volt(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18914003_batt_3_cell_status.max_volt = 0;
	if (in > 60000)
		return -1;
	in *= 1000;
	o->can_0x18914003_batt_3_cell_status.max_volt = in;
	return 0;
}

int decode_can_0x18914003_min_volt(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18914003_batt_3_cell_status.min_volt);
	rval *= 0.001;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18914003_min_volt(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18914003_batt_3_cell_status.min_volt = 0;
	if (in > 60000)
		return -1;
	in *= 1000;
	o->can_0x18914003_batt_3_cell_status.min_volt = in;
	return 0;
}

int decode_can_0x18914003_max_volt_id(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x18914003_batt_3_cell_status.max_volt_id);
	if (rval <= 63) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x18914003_max_volt_id(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x18914003_batt_3_cell_status.max_volt_id = 0;
	if (in > 63)
		return -1;
	o->can_0x18914003_batt_3_cell_status.max_volt_id = in;
	return 0;
}

int decode_can_0x18914003_min_volt_id(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x18914003_batt_3_cell_status.min_volt_id);
	if (rval <= 63) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x18914003_min_volt_id(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x18914003_batt_3_cell_status.min_volt_id = 0;
	if (in > 63)
		return -1;
	o->can_0x18914003_batt_3_cell_status.min_volt_id = in;
	return 0;
}

int print_can_0x18914003_batt_3_cell_status(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_volt = (wire: %.0f)\n", (double)(o->can_0x18914003_batt_3_cell_status.max_volt)));
	r = print_helper(r, fprintf(output, "min_volt = (wire: %.0f)\n", (double)(o->can_0x18914003_batt_3_cell_status.min_volt)));
	r = print_helper(r, fprintf(output, "max_volt_id = (wire: %.0f)\n", (double)(o->can_0x18914003_batt_3_cell_status.max_volt_id)));
	r = print_helper(r, fprintf(output, "min_volt_id = (wire: %.0f)\n", (double)(o->can_0x18914003_batt_3_cell_status.min_volt_id)));
	return r;
}

static int pack_can_0x18914004_batt_4_cell_status(can_obj_can_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* max_volt: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x18914004_batt_4_cell_status.max_volt)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* min_volt: start-bit 31, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x18914004_batt_4_cell_status.min_volt)) & 0xffff;
	x <<= 24; 
	m |= x;
	/* max_volt_id: start-bit 23, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x18914004_batt_4_cell_status.max_volt_id)) & 0xff;
	x <<= 40; 
	m |= x;
	/* min_volt_id: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x18914004_batt_4_cell_status.min_volt_id)) & 0xff;
	x <<= 16; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x18914004_batt_4_cell_status_tx = 1;
	return 8;
}

static int unpack_can_0x18914004_batt_4_cell_status(can_obj_can_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* max_volt: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x18914004_batt_4_cell_status.max_volt = x;
	/* min_volt: start-bit 31, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 24) & 0xffff;
	o->can_0x18914004_batt_4_cell_status.min_volt = x;
	/* max_volt_id: start-bit 23, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 40) & 0xff;
	o->can_0x18914004_batt_4_cell_status.max_volt_id = x;
	/* min_volt_id: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 16) & 0xff;
	o->can_0x18914004_batt_4_cell_status.min_volt_id = x;
	o->can_0x18914004_batt_4_cell_status_rx = 1;
	o->can_0x18914004_batt_4_cell_status_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x18914004_max_volt(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18914004_batt_4_cell_status.max_volt);
	rval *= 0.001;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18914004_max_volt(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18914004_batt_4_cell_status.max_volt = 0;
	if (in > 60000)
		return -1;
	in *= 1000;
	o->can_0x18914004_batt_4_cell_status.max_volt = in;
	return 0;
}

int decode_can_0x18914004_min_volt(const can_obj_can_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x18914004_batt_4_cell_status.min_volt);
	rval *= 0.001;
	if (rval <= 60000) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x18914004_min_volt(can_obj_can_h_t *o, double in) {
	assert(o);
	o->can_0x18914004_batt_4_cell_status.min_volt = 0;
	if (in > 60000)
		return -1;
	in *= 1000;
	o->can_0x18914004_batt_4_cell_status.min_volt = in;
	return 0;
}

int decode_can_0x18914004_max_volt_id(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x18914004_batt_4_cell_status.max_volt_id);
	if (rval <= 63) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x18914004_max_volt_id(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x18914004_batt_4_cell_status.max_volt_id = 0;
	if (in > 63)
		return -1;
	o->can_0x18914004_batt_4_cell_status.max_volt_id = in;
	return 0;
}

int decode_can_0x18914004_min_volt_id(const can_obj_can_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x18914004_batt_4_cell_status.min_volt_id);
	if (rval <= 63) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x18914004_min_volt_id(can_obj_can_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x18914004_batt_4_cell_status.min_volt_id = 0;
	if (in > 63)
		return -1;
	o->can_0x18914004_batt_4_cell_status.min_volt_id = in;
	return 0;
}

int print_can_0x18914004_batt_4_cell_status(const can_obj_can_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "max_volt = (wire: %.0f)\n", (double)(o->can_0x18914004_batt_4_cell_status.max_volt)));
	r = print_helper(r, fprintf(output, "min_volt = (wire: %.0f)\n", (double)(o->can_0x18914004_batt_4_cell_status.min_volt)));
	r = print_helper(r, fprintf(output, "max_volt_id = (wire: %.0f)\n", (double)(o->can_0x18914004_batt_4_cell_status.max_volt_id)));
	r = print_helper(r, fprintf(output, "min_volt_id = (wire: %.0f)\n", (double)(o->can_0x18914004_batt_4_cell_status.min_volt_id)));
	return r;
}

int unpack_message(can_obj_can_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x585: return unpack_can_0x585_mag_output(o, data, dlc, time_stamp);
	case 0xa05: return unpack_can_0xa05_motor_state(o, data, dlc, time_stamp);
	case 0x18904001: return unpack_can_0x18904001_batt_1_overall_status(o, data, dlc, time_stamp);
	case 0x18904002: return unpack_can_0x18904002_batt_2_overall_status(o, data, dlc, time_stamp);
	case 0x18904003: return unpack_can_0x18904003_batt_3_overall_status(o, data, dlc, time_stamp);
	case 0x18904004: return unpack_can_0x18904004_batt_4_overall_status(o, data, dlc, time_stamp);
	case 0x18914001: return unpack_can_0x18914001_batt_1_cell_status(o, data, dlc, time_stamp);
	case 0x18914002: return unpack_can_0x18914002_batt_2_cell_status(o, data, dlc, time_stamp);
	case 0x18914003: return unpack_can_0x18914003_batt_3_cell_status(o, data, dlc, time_stamp);
	case 0x18914004: return unpack_can_0x18914004_batt_4_cell_status(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_can_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x585: return pack_can_0x585_mag_output(o, data);
	case 0xa05: return pack_can_0xa05_motor_state(o, data);
	case 0x18904001: return pack_can_0x18904001_batt_1_overall_status(o, data);
	case 0x18904002: return pack_can_0x18904002_batt_2_overall_status(o, data);
	case 0x18904003: return pack_can_0x18904003_batt_3_overall_status(o, data);
	case 0x18904004: return pack_can_0x18904004_batt_4_overall_status(o, data);
	case 0x18914001: return pack_can_0x18914001_batt_1_cell_status(o, data);
	case 0x18914002: return pack_can_0x18914002_batt_2_cell_status(o, data);
	case 0x18914003: return pack_can_0x18914003_batt_3_cell_status(o, data);
	case 0x18914004: return pack_can_0x18914004_batt_4_cell_status(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_can_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x585: return print_can_0x585_mag_output(o, output);
	case 0xa05: return print_can_0xa05_motor_state(o, output);
	case 0x18904001: return print_can_0x18904001_batt_1_overall_status(o, output);
	case 0x18904002: return print_can_0x18904002_batt_2_overall_status(o, output);
	case 0x18904003: return print_can_0x18904003_batt_3_overall_status(o, output);
	case 0x18904004: return print_can_0x18904004_batt_4_overall_status(o, output);
	case 0x18914001: return print_can_0x18914001_batt_1_cell_status(o, output);
	case 0x18914002: return print_can_0x18914002_batt_2_cell_status(o, output);
	case 0x18914003: return print_can_0x18914003_batt_3_cell_status(o, output);
	case 0x18914004: return print_can_0x18914004_batt_4_cell_status(o, output);
	default: break; 
	}
	return -1; 
}

